# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\xiaopeiWork\thesis\mplexample\GUI\vl53.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from GUI.res_rc import *
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_vl53xxxx(object):
    def setupUi(self, vl53xxxx):
        vl53xxxx.setObjectName("vl53xxxx")
        vl53xxxx.setWindowModality(QtCore.Qt.ApplicationModal)
        vl53xxxx.resize(194, 78)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/res/uni.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        vl53xxxx.setWindowIcon(icon)
        self.horizontalLayout = QtWidgets.QHBoxLayout(vl53xxxx)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(vl53xxxx)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)

        self.retranslateUi(vl53xxxx)
        QtCore.QMetaObject.connectSlotsByName(vl53xxxx)

    def retranslateUi(self, vl53xxxx):
        _translate = QtCore.QCoreApplication.translate
        vl53xxxx.setWindowTitle(_translate("vl53xxxx", "VL53XXXX"))
        self.label.setText(_translate("vl53xxxx", "empty window"))


